### ISSUE TITLE
IE compatibility?

### ISSUE THREAD

**Issue by MrUzu** [derhuerst/svg-radar-chart#1]
Hi there,

Thanks so much for your nice work.

Sorry if my question seems dumb to u, but I was wondering how far would we be from making this code in IE?
I tried IE11, added the `<meta http-equiv="X-UA-Compatible" content="IE=edge">`, but got no success...

Any plans in this direction?

Thanks in advance for your kind answer

**Comment by derhuerst** [comment]
> I tried IE11, added the , but got no success...

Added what? Would you mind providing more details on your setup?

I'm willing to make it at least run in Edge, maybe IE11 and iOS & mobile Chrome.

**Comment by MrUzu** [comment]
Sorry, I corrected it, forgot to mark the code:
`<meta http-equiv="X-UA-Compatible" content="IE=X">`

My setup was just your example code, runned in local using a default IE

**Comment by derhuerst** [comment]
> My setup was just your example code, runned in local using a default IE

Which example? [The one under "usage"](https://github.com/derhuerst/svg-radar-chart#usage)? It won't work just like this in a browser, as it writes to `process.stdout`.

Did you bundle your code in some way, using [Browserify](https://github.com/substack/node-browserify#readme) or [Webpack](https://webpack.js.org)?

**Comment by derhuerst** [comment]
If you want to know more about how to use modern [CommonJS](https://arstechnica.com/business/2009/12/commonjs-effort-sets-javascript-on-path-for-world-domination/)-based npm modules in the browser, read [the first part of the Browserify handbook](https://github.com/substack/browserify-handbook#introduction).

**Comment by MrUzu** [comment]
thanks so much for your answer, that was actually the point, I rarely use theese tools, and finally got to the same conclusion, 

tanx again for your time

**Comment by derhuerst** [comment]
Feel free to reopen if you get into problems using `svg-radar-chart` specifically with any browser. Or if you get into problems bundling this module.
