### ISSUE TITLE
Several (sub)paths for one shape with alternating style

### ISSUE THREAD

**Issue by mattsrinc** [derhuerst/svg-radar-chart#10]
Hi, playing with your module and find it great. Now what I would like to do is to:

1. Have chart shape composed of different paths (number of them is number of columns) e.g. triangles with coordinates a center, then column value on an axis and the next column value.
2. Have alternating style (well, at least a color) for odd and even columns.

The idea is to have a way to do this radar chart (only alternating colors are the matter here):
![ref-radar-opt](https://user-images.githubusercontent.com/7528073/35177835-6e980142-fd83-11e7-96f9-f785b3649ea1.png)

I will ask about the captions in another issue.

UPDATE: the chart (image) above was most likely been created with [https://github.com/colorfulgrayscale/angular-radial-plot](https://github.com/colorfulgrayscale/angular-radial-plot) (Angular based component).

**Comment by derhuerst** [comment]
I think what you posted looks nice, but is a purely aesthetic aspect. Also, it would break the smoothing (see the website).

I would be possible to have this and the smoothing as mutually exclusive features though.

**Comment by mattsrinc** [comment]
Yes, am aware of the smoothing. Even just for one shape working (so no comparing of two or several objects) it would be nice, mutually exclusive with the smoothing.

Regarding also captions on arcs (the other issue opened by me): I have to do both features for a client and will script manually SVG tags and its values due to zeitnot. I intend to provide you the final code to you to possibly include that in svg-radar-chart in the future.

Thanks for all!

**Comment by derhuerst** [comment]
> Yes, am aware of the smoothing. Even just for one shape working (so no comparing of two or several objects) it would be nice, mutually exclusive with the smoothing.

I don't understand what you mean. My point was: Smoothing and "slices" are mutually exclusive.

> Regarding also captions on arcs (the other issue opened by me): I have to do both features for a client and will script manually SVG tags and its values due to zeitnot. I intend to provide you the final code to you to possibly include that in svg-radar-chart in the future.

Ah, okay.

**Comment by mattsrinc** [comment]
You are understood - I also thought maybe to have either several (2+) shapes with smoothing true/false (and no slices) OR having just one shape with optional slices (alternating two colors, where it makes sense for better visual effect).
