### ISSUE TITLE
How to remove the opacity of Radar shapes? 

### ISSUE THREAD

**Issue by sivadass** [derhuerst/svg-radar-chart#9]
I want to remove opacity & add box shadow of all radars. I am trying to achieve something like [this](https://res.cloudinary.com/sivadass/image/upload/v1515589611/screen-shots/radar-chart.jpg)

 Can you please guide me?

**Comment by derhuerst** [comment]
[As the readme explains, you can add any CSS using a `<style>` element.](https://github.com/derhuerst/svg-radar-chart/blob/50a9c087a646cea122beb7e36aafa9927b3e1281/readme.md#usage)

Please reopen if you have more questions or issues with this.

**Comment by sivadass** [comment]
Thanks for your help @derhuerst,  may i know how to render this chart in React JS?

Here is [code sandbox ](https://codesandbox.io/s/vj6ow20pz5) i am trying.

**Comment by derhuerst** [comment]
Well you can use ugly hacks:

- Stringify the vdom, pass it to react
- convert vdom to react-dom

Not sure if they fully work though. The proper solution would be to change `svg-radar-chart` to accept the `h` function as an option. Then, you could directly render `react-dom` trees.

**Comment by derhuerst** [comment]
> The proper solution would be to change `svg-radar-chart` to accept the `h` function as an option. Then, you could directly render `react-dom` trees.

see #14 for this.
